//
// Created by chenkuan on 2018/3/4.
//

#ifndef IOTEVENTMONITORPLATFORM_MEMORYCLIENTCONF_H
#define IOTEVENTMONITORPLATFORM_MEMORYCLIENTCONF_H

#define MEMORY_SERVER_IP "127.0.0.1"
#define MEMORY_SERVER_PORT 6666
// 事件最小长度
#define MIN_BUFFER_SIZE 50
// 事件最大长度
#define MAX_BUFFER_SIZE 4096

#endif //IOTEVENTMONITORPLATFORM_MEMORYCLIENTCONF_H
